---
title: "2021 SISBID Dimension Reduction Demo"
author: "Genevera I. Allen, Yufeng Liu, Hui Shen, Camille Little"
output:
  pdf_document: default
  html_document:
    df_print: paged
---

# Quick PCA Demo Using College Data

Load in Packages
```{r, echo = TRUE}
library(ISLR)
library(ggplot2)
library(GGally)
```

Load Digits Data
```{r, echo = TRUE}
#code for digits - ALL
rm(list=ls())
load("UnsupL_SISBID_2021.Rdata")
```


```{r, echo  = TRUE}
data(College)
cdat = College[,2:18]
dim(cdat)
names(cdat)
```

```{r, echo = TRUE}
pc = princomp(cdat) #default - centers and scales

#Go back and display these plots side by side

biplot(pc,cex=.7)
screeplot(pc)

```

scatter plots - patterns among observations
```{r, echo = TRUE}
PC1 <- as.matrix(x=pc$scores[,1]) 
PC2 <- as.matrix(pc$scores[,2])

PC <- data.frame(State = row.names(cdat), PC1, PC2)
ggplot(PC, aes(PC1, PC2)) + 
  geom_text(aes(label = State), size = 3) +
  xlab("PC1") + 
  ylab("PC2") + 
  ggtitle("First Two Principal Components of College Data")

```

Pairs Plot
```{r, echo = TRUE}
comp_labels<-c("PC1","PC2","PC3","PC4", "PC5")
pairs(pc$scores[,1:5], labels = comp_labels, main = "Pairs of PC's for College Data")
```




Loadings - variables that contribute to these patterns
```{r, echo = TRUE}

par(mfrow=c(2,1))
barplot(pc$loadings[,1],cex.names=.6,main="PC 1 Loadings")
barplot(pc$loadings[,2],cex.names=.6,main="PC 2 Loadings")
```

Variance explained
```{r, echo = TRUE}

varex = 100*pc$sdev^2/sum(pc$sdev^2)
par(mfrow=c(2,1))
screeplot(pc)
plot(varex,type="l",ylab="% Variance Explained",xlab="Component")
```


Cumulative variance explained
```{r, echo = TRUE}
#cumulative variance explained
cvarex = NULL
for(i in 1:ncol(cdat)){
  cvarex[i] = sum(varex[1:i])
}
plot(cvarex,type="l",ylab="Cumulative Variance Explained",xlab="Component", main = "Principal Component V. Variance Explained" )
```

# Sparse PCA

```{r}
library(PMA)

spc = SPC(scale(cdat),sumabsv=2,K=3)

spcL = spc$v
rownames(spcL) = names(cdat)


```

Scatterplots of Sparse PCs
```{r, echo = TRUE}
i = 1; j = 2;
plot(spc$u[,i],spc$u[,j],pch=16,cex=.2, xlab = "PC 1", ylab = "PC 2", main = "Scatterplot of Sparse PC's ")
text(spc$u[,i],spc$u[,j],rownames(cdat),cex=.6)

```



Loadings
```{r, echo = TRUE}

par(mfrow=c(2,1))
barplot(spc$v[,1],names=names(cdat),cex.names=.6,main="SPC 1 Loadings")
barplot(spc$v[,2],names=names(cdat),cex.names=.6,main="SPC 2 Loadings")

```


# Try Princomp Function for Digits 3 and 8
```{r, echo = TRUE}
dat38 = rbind(digits[which(rownames(digits)==3),],digits[which(rownames(digits)==8),])
```

```{r, echo = TRUE}
pc = princomp(dat38) #default - centers and scales
```

Pairs plot Using ggpairs
```{r, echo = TRUE}
PC1 <- as.matrix(x=pc$scores[,1]) 
PC2 <- as.matrix(pc$scores[,2])
PC3 <- as.matrix(pc$scores[,3])
PC4 <- as.matrix(pc$scores[,4])
PC5<-as.matrix(pc$scores[,5])

pc.df.digits <- data.frame(digit_name = row.names(dat38), PC1, PC2,PC3, PC4, PC5)

ggpairs(pc.df.digits, mapping = aes(color = digit_name))
```


PC Loadings
```{r, echo = TRUE}
par(mfrow=c(3,5),mar=c(.1,.1,.1,.1))
for(i in 1:15){
  imagedigit(pc$loadings[,i])
}
```

