---
title: "Install R Markdown"
author: "Genevera I. Allen & Yufeng Liu"
output:
  pdf_document: default
  html_document: default
---

# A Guide to Installing and Using R Markdown

## Install RStudio First
RStudio is a desktop application that serves as an integrated development environment for R computing language. Use the link below to install the proper version of RStudio depending on your computer.

https://rstudio.com/products/rstudio/download/

R Markdown should be included in R Studio.

For more information on R Markdown and how to use it, follow the link below.

https://rmarkdown.rstudio.com/authoring_quick_tour.html#Installation

## Topics we are covering in this module

- Dimension Reduction
- Clustering
- Testing 
- Graphical Models
- Validation


# Knit R Markdown File
In order to knit the R Markdown file, look at the top of the document and click "knit". If LaTex is not installed on your computer (LaTex is not a requirement at all), the document will default knit to an HTML file. Knit this file to make sure R Markdown is properly installed. 

# Install Packages
In order to install the packages needed to complete the labs, please refer to the r packages Rmd file ("2023_SISBID_R_packages.Rmd"). The file contains the packages needed for the module, organized by each lab. To install, place cursor on the line you would like to run and click the "Run" button at the top of the document. 

# Install Packages
Packages that need to be installed: 

- GGally
- igraph
- fastICA
- kknn
- ggplot2
- huge
- glasso
- umap
- NMF
- ISLR
- sda
- Rtsne
- tidyr
- glmnet



